security:
  providers:
    api_key_provider:
      id: App\Security\ApiKeyUserProvider

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api_write:
      pattern: ^/api/interventions
      stateless: true
      provider: api_key_provider
      custom_authenticators:
        - App\Security\ApiKeyAuthenticator
      entry_point: App\Security\ApiKeyAuthenticator
    main:
      lazy: true
      stateless: true
      provider: api_key_provider

  access_control:
    - {
        path: ^/api/interventions/\d+/close$,
        methods: [PATCH],
        roles: IS_AUTHENTICATED_FULLY,
      }
    - {
        path: ^/api/interventions$,
        methods: [POST],
        roles: IS_AUTHENTICATED_FULLY,
      }
    - { path: ^/, roles: PUBLIC_ACCESS }
