<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260828215227 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE antenna (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, city VARCHAR(255) NOT NULL, status VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_antenna_city ON antenna (city)');
        $this->addSql('CREATE INDEX idx_antenna_status ON antenna (status)');
        $this->addSql('CREATE TABLE intervention (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT NOT NULL, technician_identity VARCHAR(255) NOT NULL, priority VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, version INT DEFAULT 1 NOT NULL, antenna_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D11814ABB6FC8A64 ON intervention (antenna_id)');
        $this->addSql('CREATE INDEX idx_intervention_antenna_created ON intervention (antenna_id, created_at)');
        $this->addSql('ALTER TABLE intervention ADD CONSTRAINT FK_D11814ABB6FC8A64 FOREIGN KEY (antenna_id) REFERENCES antenna (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE intervention DROP CONSTRAINT FK_D11814ABB6FC8A64');
        $this->addSql('DROP TABLE antenna');
        $this->addSql('DROP TABLE intervention');
    }
}
